name: "General Pull Request"
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Build the component
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command

      - name: Test the component
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command
