name: Publish NPM Package
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Build the component
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command

      - name: Test the component
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command

      - name: Publish to NPM
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
